export const job = {
  header: {
    companyId: 'Company ID',
    companyName: 'Company Name',
    completedJobs: 'Completed Jobs',
    totalSMS: 'Total SMS',
  },
  data: [
    {
      companyId: '2',
      companyName: 'company g',
      completedJobs: '123',
      totalSMS: '12',
    },

    {
      companyId: '1',
      companyName: 'company f',
      completedJobs: '123',
      totalSMS: '12',
    },

    {
      companyId: '3',
      companyName: 'company e',
      completedJobs: '123',
      totalSMS: '12',
    },
    {
      companyId: '4',
      companyName: 'company d',
      completedJobs: '123',
      totalSMS: '12',
    },
    {
      companyId: '5',
      companyName: 'company c',
      completedJobs: '123',
      totalSMS: '12',
    },
    {
      companyId: '6',
      companyName: 'company b',
      completedJobs: '123',
      totalSMS: '12',
    },
    {
      companyId: '7',
      companyName: 'company a',
      completedJobs: '123',
      totalSMS: '12',
    },
  ],
}

export const api = {
  header: {
    companyName: 'Company Name',
    map: 'Map',
    direction: 'Direction',
    distanceMatrix: 'Distance Matrix',
    georecorder: 'Georecorder',
    place: 'Place',
  },

  data: [
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 123,
      georecorder: 121,
      place: 121,
    },
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 223,
      georecorder: 121,
      place: 121,
    },
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 133,
      georecorder: 121,
      place: 121,
    },
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 153,
      georecorder: 131,
      place: 121,
    },
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 123,
      georecorder: 121,
      place: 121,
    },
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 123,
      georecorder: 121,
      place: 121,
    },
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 123,
      georecorder: 121,
      place: 121,
    },
    {
      companyName: 'company a',
      map: 124,
      direction: 1231,
      distanceMatrix: 123,
      georecorder: 121,
      place: 121,
    },
  ],
}

export const jobGraphData = {
  today: [
    { time: '0.00', value: 12 },
    { time: '1.00', value: 32 },
    { time: '2.00', value: 62 },
    { time: '3.00', value: 14 },
    { time: '4.00', value: 23 },
    { time: '5.00', value: 95 },
    { time: '6.00', value: 45 },
    { time: '7.00', value: 76 },
    { time: '8.00', value: 12 },
    { time: '9.00', value: 12 },
    { time: '10.00', value: 12 },
    { time: '11.00', value: 12 },
    { time: '12.00', value: 35 },
    { time: '13.00', value: 12 },
    { time: '14.00', value: 12 },
    { time: '15.00', value: 34 },
    { time: '16.00', value: 12 },
    { time: '17.00', value: 65 },
    { time: '18.00', value: 12 },
    { time: '19.00', value: 23 },
    { time: '20.00', value: 12 },
    { time: '21.00', value: 76 },
    { time: '22.00', value: 12 },
    { time: '23.00', value: 12 },
    { time: '0.00', value: 12 },
  ],
  week: [
    { time: 'Monday', value: 12 },
    { time: 'Tuesday', value: 32 },
    { time: 'Wednesday', value: 62 },
    { time: 'Thursday', value: 14 },
    { time: 'Friday', value: 14 },
    { time: 'Saturday', value: 14 },
    { time: 'Sunday', value: 14 },
  ],
  month: [
    { time: 'week 1', value: 12 },
    { time: 'week 2', value: 32 },
    { time: 'week 3', value: 62 },
    { time: 'week 4', value: 14 },
  ],
  year: [
    { time: 'January', value: 12 },
    { time: 'February', value: 32 },
    { time: 'March', value: 62 },
    { time: 'April', value: 14 },
    { time: 'May', value: 14 },
    { time: 'June', value: 14 },
    { time: 'July', value: 14 },
    { time: 'August', value: 12 },
    { time: 'September', value: 32 },
    { time: 'October', value: 62 },
    { time: 'November', value: 14 },
    { time: 'December', value: 14 },
  ],
}

export const signupGraphData = {
  today: [
    { time: '0.00', value: 0 },
    { time: '1.00', value: 1 },
    { time: '2.00', value: 2 },
    { time: '3.00', value: 3 },
    { time: '4.00', value: 4 },
    { time: '5.00', value: 5 },
    { time: '6.00', value: 6 },
    { time: '7.00', value: 7 },
    { time: '8.00', value: 8 },
    { time: '9.00', value: 9 },
    { time: '10.00', value: 1 },
    { time: '11.00', value: 1 },
    { time: '12.00', value: 3 },
    { time: '13.00', value: 1 },
    { time: '14.00', value: 2 },
    { time: '15.00', value: 3 },
    { time: '16.00', value: 2 },
    { time: '17.00', value: 6 },
    { time: '18.00', value: 1 },
    { time: '19.00', value: 2 },
    { time: '20.00', value: 1 },
    { time: '21.00', value: 7 },
    { time: '22.00', value: 1 },
    { time: '23.00', value: 2 },
    { time: '0.00', value: 2 },
  ],
  week: [
    { time: 'Monday', value: 12 },
    { time: 'Tuesday', value: 32 },
    { time: 'Wednesday', value: 62 },
    { time: 'Thursday', value: 14 },
    { time: 'Friday', value: 14 },
    { time: 'Saturday', value: 14 },
    { time: 'Sunday', value: 14 },
  ],
  month: [
    { time: 'week 1', value: 12 },
    { time: 'week 2', value: 32 },
    { time: 'week 3', value: 62 },
    { time: 'week 4', value: 14 },
  ],
}
